development:
  adapter: postgresql
  database: meda_pulse_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: meda_pulse_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: meda_pulse_dev
  pool: 5
  timeout: 5000
